---
include:
  # - board: seeeduino_xiao_ble
  #   shield: module_tester
  #   snippet: pwm_led_key
  #   artifact-name: module_tester_pwm_led_key

  # - board: seeeduino_xiao_ble
  #   shield: module_tester
  #   snippet: trackball_pat9125
  #   artifact-name: module_tester_trackball_pat9125

  - board: seeeduino_xiao_ble
    shield: module_tester
    snippet: ec11_external_pullup
    artifact-name: module_tester_ec11_external_pullup

  # - board: seeeduino_xiao_ble
  #   shield: module_tester
  #   snippet: trackball_pmw3610_alt
  #   artifact-name: module_tester_trackball_pmw3610_alt


  # - board: seeeduino_xiao_ble
  #   shield: module_tester
  #   snippet: trackball_paw3222
  #   artifact-name: module_tester_trackball_paw3222


